name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: src
